# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import restaurant_pb2 as restaurant__pb2


class RestaurantServiceStub(object):
    """Restaurant service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRestaurant = channel.unary_unary(
                '/restaurant.RestaurantService/GetRestaurant',
                request_serializer=restaurant__pb2.RestaurantRequest.SerializeToString,
                response_deserializer=restaurant__pb2.RestaurantResponse.FromString,
                )
        self.GetRestaurants = channel.unary_unary(
                '/restaurant.RestaurantService/GetRestaurants',
                request_serializer=restaurant__pb2.RestaurantsRequest.SerializeToString,
                response_deserializer=restaurant__pb2.RestaurantsResponse.FromString,
                )
        self.AddRestaurant = channel.unary_unary(
                '/restaurant.RestaurantService/AddRestaurant',
                request_serializer=restaurant__pb2.AddRestaurantRequest.SerializeToString,
                response_deserializer=restaurant__pb2.RestaurantResponse.FromString,
                )
        self.UpdateRestaurant = channel.unary_unary(
                '/restaurant.RestaurantService/UpdateRestaurant',
                request_serializer=restaurant__pb2.UpdateRestaurantRequest.SerializeToString,
                response_deserializer=restaurant__pb2.RestaurantResponse.FromString,
                )
        self.DeleteRestaurant = channel.unary_unary(
                '/restaurant.RestaurantService/DeleteRestaurant',
                request_serializer=restaurant__pb2.DeleteRestaurantRequest.SerializeToString,
                response_deserializer=restaurant__pb2.DeleteRestaurantResponse.FromString,
                )


class RestaurantServiceServicer(object):
    """Restaurant service definition
    """

    def GetRestaurant(self, request, context):
        """Get restaurant details by ID
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRestaurants(self, request, context):
        """Get multiple restaurants
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddRestaurant(self, request, context):
        """Add a new restaurant
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateRestaurant(self, request, context):
        """Update restaurant details
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteRestaurant(self, request, context):
        """Delete a restaurant
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RestaurantServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRestaurant': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRestaurant,
                    request_deserializer=restaurant__pb2.RestaurantRequest.FromString,
                    response_serializer=restaurant__pb2.RestaurantResponse.SerializeToString,
            ),
            'GetRestaurants': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRestaurants,
                    request_deserializer=restaurant__pb2.RestaurantsRequest.FromString,
                    response_serializer=restaurant__pb2.RestaurantsResponse.SerializeToString,
            ),
            'AddRestaurant': grpc.unary_unary_rpc_method_handler(
                    servicer.AddRestaurant,
                    request_deserializer=restaurant__pb2.AddRestaurantRequest.FromString,
                    response_serializer=restaurant__pb2.RestaurantResponse.SerializeToString,
            ),
            'UpdateRestaurant': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateRestaurant,
                    request_deserializer=restaurant__pb2.UpdateRestaurantRequest.FromString,
                    response_serializer=restaurant__pb2.RestaurantResponse.SerializeToString,
            ),
            'DeleteRestaurant': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteRestaurant,
                    request_deserializer=restaurant__pb2.DeleteRestaurantRequest.FromString,
                    response_serializer=restaurant__pb2.DeleteRestaurantResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'restaurant.RestaurantService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RestaurantService(object):
    """Restaurant service definition
    """

    @staticmethod
    def GetRestaurant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/restaurant.RestaurantService/GetRestaurant',
            restaurant__pb2.RestaurantRequest.SerializeToString,
            restaurant__pb2.RestaurantResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRestaurants(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/restaurant.RestaurantService/GetRestaurants',
            restaurant__pb2.RestaurantsRequest.SerializeToString,
            restaurant__pb2.RestaurantsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AddRestaurant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/restaurant.RestaurantService/AddRestaurant',
            restaurant__pb2.AddRestaurantRequest.SerializeToString,
            restaurant__pb2.RestaurantResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateRestaurant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/restaurant.RestaurantService/UpdateRestaurant',
            restaurant__pb2.UpdateRestaurantRequest.SerializeToString,
            restaurant__pb2.RestaurantResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteRestaurant(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/restaurant.RestaurantService/DeleteRestaurant',
            restaurant__pb2.DeleteRestaurantRequest.SerializeToString,
            restaurant__pb2.DeleteRestaurantResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
