# Generated by Django 5.1.6 on 2025-07-28 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the restaurant', max_length=200)),
                ('address', models.TextField(help_text='Full address of the restaurant')),
                ('phone_number', models.CharField(help_text='Contact phone number', max_length=20)),
                ('rating', models.DecimalField(decimal_places=2, help_text='Rating from 0.0 to 5.0', max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'ordering': ['-created_at'],
            },
        ),
    ]
